# Generated by Django 5.2.4 on 2026-01-03 21:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_tag_card_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='tags',
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Criado'), ('title_changed', 'Título alterado'), ('description_changed', 'Descrição alterada'), ('priority_changed', 'Prioridade alterada'), ('assigned', 'Atribuído'), ('unassigned', 'Desatribuído'), ('due_date_changed', 'Data de vencimento alterada'), ('moved', 'Movido para outra coluna'), ('completed', 'Marcado como concluído'), ('reopened', 'Reabrindo'), ('comment_added', 'Comentário adicionado'), ('tag_added', 'Tag adicionada'), ('tag_removed', 'Tag removida')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='boards.card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
