# Generated by Django 5.2.4 on 2026-01-05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0009_boardmember_invited_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_memberships', to='auth.user'),
        ),
    ]
